""" Constants file """
import math

BATCH_SIZE = 8
EPOCHS = 2
OUTPUT_DIMENSION = 80
QUANTIZATION_BITS = 3
M = int(math.pow(2, QUANTIZATION_BITS))
QUANTIZATION_RATE = QUANTIZATION_BITS/OUTPUT_DIMENSION
