""" Constants file """
import math

BATCH_SIZE = 8
EPOCHS = 2
INPUT_DIMENSION = 240
OUTPUT_DIMENSION = 80
QUANTIZATION_BITS = 3
M = int(math.pow(2, QUANTIZATION_BITS))
QUANTIZATION_RATE = QUANTIZATION_BITS*OUTPUT_DIMENSION/INPUT_DIMENSION
CODEBOOK_LR = 0.01
